In [ ]:
# MACHINE LEARNING LAB - CSE 3008
#--------------------------------
# NAME: R B Ch S Tarun

# Date: 28 - OCT - 2021


#MOUNTING THE GOOGLE DRIVE TO ACCESSING THE CONTENTS..
from google.colab import drive
drive.mount('/content/gdrive',force_remount = True)

Mounted at /content/gdrive


In [ ]:
# Importing libraries
import numpy as np 
import pandas as pd 
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.datasets import load_iris
import sklearn.metrics as metrics


In [ ]:
#Importing the data from drive
iris = pd.read_csv('/content/gdrive/MyDrive/ML_Lab/Iris.csv')
print ("Dataset Shape: ", iris.shape) 
print ("Dataset: ",iris.head()) 

Dataset Shape:  (150, 6)
Dataset:     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [ ]:
X = iris.values[:, 0:4] 
Y = iris.values[:, 5]
print(X[0:5])
print(Y[0:5])
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.5)

clfr= RandomForestClassifier(n_estimators=150)
clfr.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
 criterion='gini', max_depth=None, max_features='auto',
 max_leaf_nodes=None, max_samples=None,
 min_impurity_decrease=0.0, min_impurity_split=None,
 min_samples_leaf=1, min_samples_split=2,
 min_weight_fraction_leaf=0.0, n_estimators=150,
 n_jobs=None, oob_score=False, random_state=None,
 verbose=0, warm_start=False)
Y_pred=clfr.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, Y_pred))

# We getting the accuracy of 1 might be due to the random picks of values

[[1 5.1 3.5 1.4]
 [2 4.9 3.0 1.4]
 [3 4.7 3.2 1.3]
 [4 4.6 3.1 1.5]
 [5 5.0 3.6 1.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']
Accuracy: 1.0
